logbook/urls.py
# logbook.urls
# Application url definition and routers.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Fri Aug 21 13:21:31 2015 -0500
#
# Copyright (C) 2015 District Data Labs
# For license information, see LICENSE.txt
#
# ID: urls.py [6e3ca6b] benjamin@bengfort.com $

"""
Application url definition and routers.
"""

##########################################################################
## Imports
##########################################################################

from django.contrib import admin
from rest_framework import routers
from django.conf.urls import include, url

from django.views.generic import TemplateView

from logbook.views import *
from members.views import *
from catalog.views import *

##########################################################################
## Endpoint Discovery
##########################################################################

## API
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'status', HeartbeatViewSet, "status")

##########################################################################
## URL Patterns
##########################################################################

urlpatterns = [
    # Admin URLs
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Application URLs
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^terms/$', TemplateView.as_view(template_name='site/legal/terms.html'), name='terms'),
    url(r'^privacy/$', TemplateView.as_view(template_name='site/legal/privacy.html'), name='privacy'),
    url(r'^upload/$', DatasetUploadView.as_view(), name='upload'),
    url(r'^upload/link-fetch/$', PublicationLinkFetch.as_view(), name='upload-link'),

    # Members URLs
    url(r'^members/$', MemberListView.as_view(), name='member-list'),
    url(r'^members/(?P<slug>[\w-]+)/$', MemberView.as_view(), name='member-detail'),

    # Authentication URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('^accounts/', include('django.contrib.auth.urls')),

    ## REST API Urls
    url(r'^api/', include(router.urls, namespace="api")),
]

catalog/models.py
# catalog.models
# Models that define how we describe DDL events in the database.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Fri Aug 21 16:27:03 2015 -0500
#
# Copyright (C) 2015 District Data Labs
# For license information, see LICENSE.txt
#
# ID: models.py [7072b57] benjamin@bengfort.com $

"""
Models that define how we describe DDL events in the database.
"""

##########################################################################
## Imports
##########################################################################

from django.db import models
from model_utils import Choices
from autoslug import AutoSlugField
from markupfield.fields import MarkupField
from model_utils.models import TimeStampedModel
from logbook.utils import nullable, humanizedelta
from django.core.urlresolvers import reverse

##########################################################################
## Event Base Class
##########################################################################

class DDLEvent(TimeStampedModel):
    """
    Defines fields that all DDL events share no matter their event type.
    """

    name     = models.CharField(max_length=255)
    slug     = AutoSlugField(populate_from='name', unique=True)
    begins   = models.DateTimeField(**nullable)
    finishes = models.DateTimeField(**nullable)
    details  = MarkupField(markup_type='markdown', help_text='Edit in Markdown', **nullable)

    class Meta:
        abstract = True

    def duration(self, humanize=False):
        """
        Returns the duration of the event, either in seconds or as a humanized
        time stamp (e.g. the number of days, hours, etc.).
        """
        seconds = (self.finishes - self.begins).total_seconds()
        if humanize:
            return humanizedelta(seconds=seconds)
        return seconds

    def get_absolute_url(self):
        """
        Return the detail view of the event object.
        """
        raise NotImplementedError("DDL Events shoud have a page view!")

    def __str__(self):
        return self.name


##########################################################################
## Courses
##########################################################################

class Course(DDLEvent):
    """
    Almost everything DDL offers is a course, from a Webinar to a Workshop.
    This database field will track courses and their instructors as well as
    other important information about the course.

    Note that longer events like Incubators and Research Labs are not this.
    """

    TYPES  = Choices('workshop', 'webinar', 'lecture')

    course_type = models.CharField(max_length=10, choices=TYPES, default=TYPES.workshop)
    instructors = models.ManyToManyField('auth.User', through='catalog.Instructor', related_name='taught_courses')
    students    = models.ManyToManyField('auth.User', through='catalog.Enrollment', related_name='enrolled_courses')

    class Meta:
        db_table = 'courses'
        ordering = ('-begins', '-created')
        get_latest_by   = 'created'
        unique_together = ('name', 'begins')

    def get_absolute_url(self):
        """
        Return the detail view of the Course object
        """
        return reverse('course', kwargs={'slug': self.slug})

    def __str__(self):
        return "{} on {}".format(self.name, self.begins.strftime('%b %d, %Y'))


##########################################################################
## Instructors & Enrollment: relationships between users and courses.
##########################################################################

class Instructor(TimeStampedModel):
    """
    A relationship between a user and a course that describes how they
    instructed the course. Note this is similar to the members.Membership
    relationship, but between courses and users, not profiles and roles.
    """

    course = models.ForeignKey('catalog.Course')
    user   = models.ForeignKey('auth.User')
    role   = models.ForeignKey('members.Role', related_name='+')

    class Meta:
        db_table = 'instructors'
        ordering = ('-created',)
        get_latest_by   = 'created'
        unique_together = ('user', 'course', 'role')

    def __str__(self):
        return "{} teaching {}".format(self.user.profile.full_name, self.course)


class Enrollment(TimeStampedModel):
    """
    A relationship between a user and a course that describes their enrollment
    and participation in a course. This is similar to Instructor
    """

    GRADES = Choices(
                ('SC', 'Satisfactory Completion'),
                ('I',  'Incomplete'),
                ('RE', 'Registered, but Never Attended'),
                ('AT', 'Attendance Verfied'),
                ('W',  'Withdrawn'),
             )

    course = models.ForeignKey('catalog.Course')
    user   = models.ForeignKey('auth.User')
    result = models.CharField(max_length=2, choices=GRADES, **nullable)

    class Meta:
        db_table = 'enrollment'
        ordering = ('-created',)
        get_latest_by   = 'created'

    def __str__(self):
        return "{} enrolled in {}".format(self.user.profile.full_name, self.course)


##########################################################################
## Subscriptions and Blog Posts
##########################################################################

class Subscription(TimeStampedModel):
    """
    A subscription service is a newsletter or RSS feed that DDL members can
    subscribe to. Subscriptions make the user a DDL reader (see roles).
    """

    name     = models.CharField(max_length=255)
    slug     = AutoSlugField(populate_from='name', unique=True)
    details  = MarkupField(markup_type='markdown', help_text='Edit in Markdown', **nullable)
    link     = models.URLField(**nullable)
    subscribers = models.ManyToManyField('auth.User', related_name='subscriptions', blank=True)

    class Meta:
        db_table = 'subscriptions'

    def __str__(self):
        return self.name

class Publication(TimeStampedModel):
    """
    A publication is a blog post, an article, tutorial or some writing that has
    been contributed by DDL authors (see roles).
    """

    TYPES    = Choices('blog', 'tutorial', 'paper', 'slides', 'book')

    title    = models.CharField(max_length=255)
    slug     = AutoSlugField(populate_from='title', unique=True)
    link     = models.URLField(**nullable)
    pubdate  = models.DateField(**nullable)
    pubtype  = models.CharField(max_length=12, choices=TYPES, default=TYPES.blog)
    authors  = models.ManyToManyField('auth.User', related_name='publications', blank=True)

    class Meta:
        db_table = 'publications'
        ordering = ('-pubdate', '-created')
        get_latest_by = 'pubdate'

    def __str__(self):
        return self.title

    @property
    def byline(self):
        """
        Returns the comma separated byline for the authors.
        """
        num_authors = self.authors.count()

        # Handle various counts of authors
        if num_authors == 1:
            return self.authors.first().profile.full_name
        elif num_authors == 2:
            return " and ".join([a.profile.full_name for a in self.authors.all()])
        else:
            return "{}, et al.".format(self.authors.first().last_name)

catalog/forms.py
# catalog.forms
# Forms and other HTML data handling from the web front end.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Wed Oct 28 15:47:44 2015 -0400
#
# Copyright (C) 2015 District Data Labs
# For license information, see LICENSE.txt
#
# ID: forms.py [b52230a] benjamin@bengfort.com $

"""
Forms and other HTML data handling from the web front end.
"""

##########################################################################
## Imports
##########################################################################

import requests

from django import forms
from bs4 import BeautifulSoup
from datetime import datetime
from django.conf import settings
from urllib.parse import urlparse
from autoslug.settings import slugify
from catalog.parser import slugify as username_slugify
from django.contrib.auth.models import User

from catalog.models import Publication
from catalog.parser import ActivityParser
from members.models import Membership, Role

##########################################################################
## Module Constants
##########################################################################

PUBDATE_FORMAT = "%B %d, %Y"

DATASET_ERROR_MSGS = {
    "required": "Please select an activity dataset to upload.",
    "invalid": "The activity dataset you provided is invalid, please select another.",
    "missing": "The activity dataset you specified is missing, please select another.",
    "empty": "The uploaded activity dataset is empty, cannot upload.",
    "max_length": "The activity dataset is too big, please submit a smaller CSV.",
}

##########################################################################
## Upload Form
##########################################################################


class DatasetUploadForm(forms.Form):
    """
    Post an activity dataset and add the activity to the logbook.
    """

    dataset = forms.FileField(required=True, error_messages=DATASET_ERROR_MSGS)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(DatasetUploadForm, self).__init__(*args, **kwargs)

    def save(self):
        """
        Parse the dataset
        """
        parser  = ActivityParser()
        dataset = self.cleaned_data['dataset']

        # Execute the parsing
        dataset.open('rb')
        counts  = parser.parse(dataset)
        dataset.close()

        return counts


class LinkFetchForm(forms.Form):
    """
    Submit a URL to lookup the publication.
    """

    link   = forms.URLField(required=True)


    def clean_link(self):
        """
        Validate a link such that its domain is in the list of valid
        publication domains and that we haven't already added the link to the
        database (because then there is nothing we can do).
        """

        data = self.cleaned_data['link']
        urlp = urlparse(data)

        # Test to ensure is in the valid domains
        if urlp.netloc not in settings.PUBLICATION_DOMAINS:
            raise forms.ValidationError(
                "Domain {!r} is not a valid publication domain. "
                "Only DDL publications can be fetched."
                .format(urlp.netloc,)
            )

        # If the link is in the DB - don't do any work.
        if Publication.objects.filter(link=data).exists():
            raise forms.ValidationError(
                "This link has already been added to the database!"
            )

        return data

    def get_author(self, name):
        """
        Attempts to retrieve an author by the full name from the database.
        """
        parts = name.split()
        uname = parts[0][0] + parts[-1] if len(parts) > 1 else parts[0]
        uname = username_slugify(uname)
        return User.objects.get(username=uname)

    def fetch(self):
        """
        Fetches the blog post, parses it and returns a dictionary of relevant
        values and information. Use this method sparingly.
        """
        link = self.cleaned_data['link']
        resp = requests.get(link)
        soup = BeautifulSoup(resp.content, "html5lib")

        return {
            "title": soup.find(class_='kaia_header_title').text.strip(),
            "authors": soup.find(class_="name_link").text.strip().split(" and "),
            "pubdate": datetime.strptime(soup.find(class_="entry_date").text.strip(), PUBDATE_FORMAT).date(),
            "link": link,
        }

    def save(self):
        """
        Parses and saves the publication to the database.
        """
        kwargs   = self.fetch()

        # Fetch authors first to error early if we can't find the user.s
        authors  = [
            self.get_author(name) for name in kwargs.pop('authors', [])
        ]

        # Get publication by slug or create it with the discovered attributes
        pub, crt = Publication.objects.update_or_create(slug=slugify(kwargs['title']), defaults=kwargs)

        # Add authors to the publication if any
        for author in authors:
            # Make sure the author has the correct role
            _ = Membership.objects.get_or_create(
                role=Role.objects.get(slug="blog-author"), profile=author.profile
            )

            # Add author to the publication
            if author not in pub.authors.all():
                pub.authors.add(author)

        return pub, crt

logbook/views.py
# logbook.views
# Default application views for the system.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Fri Aug 21 13:20:11 2015 -0500
#
# Copyright (C) 2015 District Data Labs
# For license information, see LICENSE.txt
#
# ID: views.py [63baf66] benjamin@bengfort.com $

"""
Default application views for the system.
"""

##########################################################################
## Imports
##########################################################################

import logbook

from datetime import datetime

from braces.views import LoginRequiredMixin
from django.views.generic import TemplateView

from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.permissions import AllowAny

# Temporary context for home dashboard view
from catalog.models import *
from members.models import *

##########################################################################
## Views
##########################################################################

class HomePageView(LoginRequiredMixin, TemplateView):

    template_name = "site/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['courses'] = Course.objects.all()
        context['publications'] = Publication.objects.all()
        context['roles'] = Role.objects.all()
        context['counts'] = {}

        for model in (Course, Instructor, Enrollment, Subscription, Publication, Role, Membership, Profile):
            context['counts'][model._meta.verbose_name_plural.title()] = model.objects.count()

        return context

##########################################################################
## API Views for this application
##########################################################################

class HeartbeatViewSet(viewsets.ViewSet):
    """
    Endpoint for heartbeat checking, including the status and version.
    """

    permission_classes = (AllowAny,)

    def list(self, request):
        return Response({
            "status": "ok",
            "version": logbook.get_version(),
            "timestamp": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        })

logbook/templates/site/home.html
{% extends 'page.html' %}

{% block content %}

  <div class="container">
    <!-- Primary content area -->
    <div class="row">

      <!-- Page Title Area -->
      <div class="col-xs-12">
        <div class="page-header">
          <h2>Logbook Dashboard <small>Application Status</small></h2>
        </div>
      </div>

      <!-- Breadcrumbs navigation area -->
      <div class="col-sm-12">
        <ol class="breadcrumb">
          <li class="active"><i class="fa fa-home"></i> Home</li>
        </ol>
      </div>

      <!-- At-a-glance overview two column panel -->
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Roles</h3>
            </div>
            <ul class="list-group">
              {% for role in roles %}
              {% if role.members.count > 0 %}
              <li class="list-group-item">
                <span class="badge">{{ role.members.count }}</span>
                {{ role }}
              </li>
              {% endif %}
              {% empty %}
              <li class="list-group-item">No roles added yet.</li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Table Counts</h3>
            </div>
            <ul class="list-group">
              {% for model, count in counts.items %}
              {% if count > 0 %}
              <li class="list-group-item">
                <span class="badge">{{ count }}</span>
                {{ model }}
              </li>
              {% endif %}
              {% empty %}
              <li class="list-group-item">No tables populated yet.</li>
              {% endfor %}
            </ul>
          </div>
        </div>


      <!-- Courses overview panel -->
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Course Overview</h3>
          </div>
          <table class="table table-striped table-hoever">
            <thead>
              <th>Title</th>
              <th>Date</th>
              <th>Instructors</th>
              <th class="text-center">Students</th>
            </thead>
            <tbody>
              {% for course in courses %}
              <tr>
                <td>{{ course.name }}</td>
                <td>{{ course.begins }}</td>
                <td>{% for i in course.instructors.all %}{% if not forloop.first %}, {% endif %}<a href="{{ i.profile.get_absolute_url }}">{{ i.profile.full_name }}</a>{% endfor %}</td>
                <td class="text-center">{{ course.students.count }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="4">No courses discovered</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      <!-- Publications overview panel -->
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Publications Overview</h3>
          </div>
          <table class="table table-striped table-hoever">
            <thead>
              <th>Title</th>
              <th>Publication Date</th>
              <th>Type</th>
              <th>Authors</th>
            </thead>
            <tbody>
              {% for pub in publications %}
              <tr>
                <td>{% if pub.link %}<a href="{{ pub.link }}" title="{{ pub.title }}" target="_blank">{% endif %}{{ pub.title }}{% if pub.link %}</a>{% endif %}</td>
                <td>{{ pub.pubdate }}</td>
                <td>{{ pub.get_pubtype_display|title }}</td>
                <td>{% for a in pub.authors.all %}{% if not forloop.first %}, {% endif %}<a href="{{ a.profile.get_absolute_url }}">{{ a.profile.full_name }}</a>{% endfor %}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="4">No publications discovered</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>


    </div><!-- primary content area ends -->
  </div><!-- container ends -->

{% endblock %}

logbook/templates/site/link-fetch.html
{% extends 'page.html' %}
{% load staticfiles %}

{% block stylesheets %}
  {{ block.super }}
  <style type="text/css">
    #loading-overlay {
      position: fixed;
      width: 100%;
      height:100%;
      display: flex;
      align-items: center;
      top: 0;
      background-color: #333;
      opacity: 0.75;
      z-index: 9999;
    }

    .plus {
      display: flex;
      margin: 0 auto;
      font-size: 36px;
      color: #FFF;
    }
  </style>
{% endblock %}

{% block content %}

    <div class="container">
      <!-- Primary content area -->
      <div class="row">

        <!-- Page Title Area -->
        <div class="col-xs-12">
          <div class="page-header">
            <h2>Fetch Publication by URL</h2>
          </div>
        </div>

        <!-- Breadcrumbs navigation area -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{% url 'upload' %}"><i class="fa fa-upload"></i> Upload</a></li>
            <li class="active"><i class="fa fa-link"></i> Link Fetch</li>
          </ol>
        </div>

        <!-- Alerts and Messages -->
        {% include 'components/form-alerts.html' %}

        <!-- Link Fetch Form -->
        <div class="col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">Add Publication by Link</h4>
            </div>
            <div class="panel-body">
              <form action="" method="POST">
                <div class="input-group">
                  <input type="text" class="form-control" name="link" id="id_link" placeholder="Enter URL of Publication">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Submit</button>
                  </span>
                </div><!-- /input-group -->
                {% csrf_token %}
              </form>
            </div>
          </div>
        </div>

      </div><!-- primary content area ends -->
    </div><!-- container ends -->

    <!-- Loading Overlay -->
    <div id="loading-overlay" class="hidden">
      <div class="plus">
        <i class="fa fa-spin fa-spinner"></i>
      </div>
    </div>

{% endblock %}

{% block javascripts %}
  {{ block.super }}
  <script type="text/javascript">
    $(document).ready(function() {

      // add the loading context to the screen.
      function loading() {
        $("#loading-overlay").removeClass("hidden");
      }

      console.log("Trinket Uploader is started and ready!");
    });
  </script>
{% endblock %}

logbook/templates/site/upload.html
{% extends 'page.html' %}
{% load staticfiles %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/upload.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
      <!-- Primary content area -->
      <div class="row">

        <!-- Page Title Area -->
        <div class="col-xs-12">
          <div class="page-header">
            <h2 class="pull-left">Upload Activity Dataset</h2>
            <a href="{% url 'upload-link' %}" title="Add publication by URL" class="btn btn-primary pull-right" style="margin-top:21px">
              <i class="fa fa-file-text"></i> Add Blog Post
            </a>
            <div class="clearfix"></div>
          </div>
        </div>

        <!-- Breadcrumbs navigation area -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active"><i class="fa fa-upload"></i> Upload</li>
          </ol>
        </div>

       {% include 'components/form-alerts.html' %}

        <!-- Upload Panel -->
        <div class="col-xs-12">
          <div class="panel panel-default">
  				  <div class="panel-heading">
              <h3 class="panel-title">Upload Activity Dataset</h3>
            </div>
  				  <div class="panel-body">
              <form class="dataset-upload-form" action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">

                <div class="input-group image-preview">
  						    <input placeholder="" type="text" class="form-control image-preview-filename" disabled="disabled">
  						    <span class="input-group-btn">
  						      <!-- image-preview-clear button -->
  						      <button type="button" class="btn btn-default image-preview-clear hidden">
                      <i class="fa fa-trash"></i> Clear
                    </button>

                    <!-- image-preview-input -->
                    <!-- Cleverly hide a file upload button in front of another button -->
  						      <div class="btn btn-default image-preview-input">
                      <i class="fa fa-folder-open"></i> <span class="image-preview-input-title">Browse</span>
  							      <input type="file" accept="text/csv, application/csv, application/vnd.ms-excel" name="dataset"/>
  						      </div>

                    <!-- Upload button -->
                    <button type="submit" class="btn btn-labeled btn-default">
                      <span class="btn-label"><i class="fa fa-upload"></i> </span>Upload</button>
  						    </span>
                </div>
                {% csrf_token %}
              </form>

    					<!-- Drop Zone -->
              <form id="dropForm" class="dataset-upload-form" action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">
    					<div class="upload-drop-zone" id="drop-zone">
                Or drag and drop dataset here
                <input type="file" name="dataset" />
              </div>
              {% csrf_token %}
              </form>

    				</div><!-- upload panel body ends -->
          </div><!-- upload panel ends -->
        </div><!-- upload panel row ends -->

        {% if report %}
        <div class="col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Upload Activity Report</h3>
            </div>
            <ul class="list-group">
            {% for item, count in report %}
              <li class="list-group-item">
                <span class="badge">{{ count }}</span>
                {{ item }}
              </li>
            {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}


      </div><!-- primary content area ends -->
    </div><!-- container ends -->

    <!-- Loading Overlay -->
    <div id="loading-overlay" class="hidden">
      <div class="plus">
        <i class="fa fa-spin fa-spinner"></i>
      </div>
    </div>

{% endblock %}

{% block javascripts %}
  {{ block.super }}
  <script type="text/javascript">
    $(document).ready(function() {

      // add the loading context to the screen.
      function loading() {
        $("#loading-overlay").removeClass("hidden");
      }

      // Display preview in text body on file selection
      $("input[type=file]").change(function(e) {
        var fullPath = $(e.target).val();
        if (fullPath) {
        	var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
        	var filename = fullPath.substring(startIndex);
        	if (filename.indexOf('\\') === 0 || filename.indexOf('/') === 0) {
        		filename = filename.substring(1);
        	}
          $(".image-preview-filename").val(filename);
        }
      });

      $(".upload-drop-zone").on("dragenter", function(e) {
        $(".upload-drop-zone").addClass("drop");
      });

      $(".upload-drop-zone").on("dragleave", function(e) {
        $(".upload-drop-zone").removeClass("drop");
      });

      $(".upload-drop-zone input[type=file]").change(function(e) {
        loading();
        $("#dropForm").submit();
      });

      $(".dataset-upload-form").submit(function(e) {
        loading();
      });


      console.log("Trinket Uploader is started and ready!");
    });
  </script>
{% endblock %}